# HBD Application Configuration

[database]
# Database connection settings
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
database = "mysql"
initialize_canned_data = false

[database.pool]
# Connection pool settings
min_connections = 1
max_connections = 10
connection_timeout = 30  # seconds
idle_timeout = 600       # seconds

[server]
# HTTP server settings
host = "0.0.0.0"
port = 3000
request_timeout = 30     # seconds
enable_cors = true
max_body_size = 1048576  # 1MB in bytes

[logging]
# Logging configuration
level = "info"           # trace, debug, info, warn, error
file_enabled = true
file_path = "logs/app.log"
console_enabled = true
syslog_enabled = true
max_file_size = 10       # MB
max_files = 5

[app]
# Application settings
name = "hbd"
version = "0.0.0"
environment = "development"  # development, staging, production
debug = false

# Optional cache configuration (uncomment if needed)
# [app.cache]
# default_interval = 300   # seconds (5 minutes)
# max_interval = 3600      # seconds (1 hour)
# auto_cleanup = true
# cleanup_interval = 24    # hours
# max_record_age = 30      # days
